# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'database_project.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(1124, 635)
        self.label = QtWidgets.QLabel(Form)
        self.label.setGeometry(QtCore.QRect(10, 10, 491, 41))
        font = QtGui.QFont()
        font.setFamily("3ds")
        font.setPointSize(20)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.tabWidget = QtWidgets.QTabWidget(Form)
        self.tabWidget.setGeometry(QtCore.QRect(6, 50, 1115, 581))
        font = QtGui.QFont()
        font.setFamily("3ds")
        font.setPointSize(14)
        font.setBold(False)
        font.setWeight(50)
        self.tabWidget.setFont(font)
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.pushButton = QtWidgets.QPushButton(self.tab)
        self.pushButton.setGeometry(QtCore.QRect(910, 450, 171, 61))
        self.pushButton.setObjectName("pushButton")
        self.layoutWidget = QtWidgets.QWidget(self.tab)
        self.layoutWidget.setGeometry(QtCore.QRect(10, 20, 361, 141))
        self.layoutWidget.setObjectName("layoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.layoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.label_2 = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(13)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 0, 0, 1, 1)
        self.dateEdit = QtWidgets.QDateEdit(self.layoutWidget)
        self.dateEdit.setDateTime(QtCore.QDateTime(QtCore.QDate(2019, 4, 22), QtCore.QTime(0, 0, 0)))
        self.dateEdit.setMaximumDateTime(QtCore.QDateTime(QtCore.QDate(2019, 6, 30), QtCore.QTime(0, 0, 0)))
        self.dateEdit.setMinimumDateTime(QtCore.QDateTime(QtCore.QDate(2019, 3, 15), QtCore.QTime(0, 0, 0)))
        self.dateEdit.setMaximumDate(QtCore.QDate(2019, 6, 30))
        self.dateEdit.setCalendarPopup(True)
        self.dateEdit.setObjectName("dateEdit")
        self.gridLayout.addWidget(self.dateEdit, 0, 1, 1, 1)
        self.comboBox = QtWidgets.QComboBox(self.layoutWidget)
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.gridLayout.addWidget(self.comboBox, 1, 1, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.layoutWidget)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 2, 0, 1, 1)
        self.comboBox_2 = QtWidgets.QComboBox(self.layoutWidget)
        self.comboBox_2.setObjectName("comboBox_2")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.gridLayout.addWidget(self.comboBox_2, 2, 1, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(13)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 1, 0, 1, 1)
        self.tableWidget = QtWidgets.QTableWidget(self.tab)
        self.tableWidget.setGeometry(QtCore.QRect(390, 20, 691, 411))
        font = QtGui.QFont()
        font.setFamily("3ds")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.tableWidget.setFont(font)
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(6)
        self.tableWidget.setRowCount(6)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(5, item)
        self.planemode = QtWidgets.QCheckBox(self.tab)
        self.planemode.setGeometry(QtCore.QRect(12, 212, 110, 21))
        font = QtGui.QFont()
        font.setFamily("3ds")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.planemode.setFont(font)
        self.planemode.setObjectName("planemode")
        self.label_16 = QtWidgets.QLabel(self.tab)
        self.label_16.setGeometry(QtCore.QRect(11, 176, 151, 20))
        font = QtGui.QFont()
        font.setFamily("3ds")
        font.setPointSize(14)
        font.setBold(False)
        font.setWeight(50)
        self.label_16.setFont(font)
        self.label_16.setObjectName("label_16")
        self.planeselect = QtWidgets.QComboBox(self.tab)
        self.planeselect.setGeometry(QtCore.QRect(130, 207, 151, 30))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.planeselect.setFont(font)
        self.planeselect.setObjectName("planeselect")
        self.planeselect.addItem("")
        self.planeselect.addItem("")
        self.planeselect.addItem("")
        self.planeselect.addItem("")
        self.directflight = QtWidgets.QCheckBox(self.tab)
        self.directflight.setGeometry(QtCore.QRect(12, 256, 111, 21))
        font = QtGui.QFont()
        font.setFamily("3ds")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.directflight.setFont(font)
        self.directflight.setObjectName("directflight")
        self.planeage = QtWidgets.QCheckBox(self.tab)
        self.planeage.setGeometry(QtCore.QRect(12, 299, 131, 20))
        font = QtGui.QFont()
        font.setFamily("3ds")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.planeage.setFont(font)
        self.planeage.setObjectName("planeage")
        self.mdiArea = QtWidgets.QMdiArea(self.tab)
        self.mdiArea.setGeometry(QtCore.QRect(450, 170, 200, 160))
        self.mdiArea.setObjectName("mdiArea")
        self.mdiArea.raise_()
        self.pushButton.raise_()
        self.layoutWidget.raise_()
        self.tableWidget.raise_()
        self.planemode.raise_()
        self.label_16.raise_()
        self.planeselect.raise_()
        self.directflight.raise_()
        self.planeage.raise_()
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.label_5 = QtWidgets.QLabel(self.tab_2)
        self.label_5.setGeometry(QtCore.QRect(9, 456, 110, 20))
        self.label_5.setObjectName("label_5")
        self.comboBox_3 = QtWidgets.QComboBox(self.tab_2)
        self.comboBox_3.setGeometry(QtCore.QRect(9, 482, 104, 26))
        self.comboBox_3.setObjectName("comboBox_3")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.label_6 = QtWidgets.QLabel(self.tab_2)
        self.label_6.setGeometry(QtCore.QRect(125, 456, 55, 20))
        self.label_6.setObjectName("label_6")
        self.comboBox_4 = QtWidgets.QComboBox(self.tab_2)
        self.comboBox_4.setGeometry(QtCore.QRect(125, 482, 104, 26))
        self.comboBox_4.setObjectName("comboBox_4")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.label_7 = QtWidgets.QLabel(self.tab_2)
        self.label_7.setGeometry(QtCore.QRect(235, 456, 171, 20))
        self.label_7.setObjectName("label_7")
        self.label_8 = QtWidgets.QLabel(self.tab_2)
        self.label_8.setGeometry(QtCore.QRect(470, 455, 141, 20))
        self.label_8.setObjectName("label_8")
        self.lineEdit = QtWidgets.QLineEdit(self.tab_2)
        self.lineEdit.setGeometry(QtCore.QRect(235, 482, 218, 26))
        self.lineEdit.setObjectName("lineEdit")
        self.lineEdit_2 = QtWidgets.QLineEdit(self.tab_2)
        self.lineEdit_2.setGeometry(QtCore.QRect(470, 480, 218, 26))
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.pushButton_2 = QtWidgets.QPushButton(self.tab_2)
        self.pushButton_2.setGeometry(QtCore.QRect(920, 460, 141, 51))
        self.pushButton_2.setObjectName("pushButton_2")
        self.tableWidget_2 = QtWidgets.QTableWidget(self.tab_2)
        self.tableWidget_2.setGeometry(QtCore.QRect(0, 10, 1071, 401))
        self.tableWidget_2.setObjectName("tableWidget_2")
        self.tableWidget_2.setColumnCount(5)
        self.tableWidget_2.setRowCount(6)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setVerticalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setVerticalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setVerticalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setVerticalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setVerticalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(4, item)
        self.tabWidget.addTab(self.tab_2, "")
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.label_10 = QtWidgets.QLabel(self.tab_3)
        self.label_10.setGeometry(QtCore.QRect(20, 10, 271, 41))
        self.label_10.setObjectName("label_10")
        self.tableWidget_3 = QtWidgets.QTableWidget(self.tab_3)
        self.tableWidget_3.setGeometry(QtCore.QRect(20, 70, 1051, 391))
        self.tableWidget_3.setObjectName("tableWidget_3")
        self.tableWidget_3.setColumnCount(4)
        self.tableWidget_3.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_3.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_3.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_3.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_3.setHorizontalHeaderItem(3, item)
        self.comboBox_6 = QtWidgets.QComboBox(self.tab_3)
        self.comboBox_6.setGeometry(QtCore.QRect(300, 20, 276, 26))
        self.comboBox_6.setObjectName("comboBox_6")
        self.comboBox_6.addItem("")
        self.comboBox_6.addItem("")
        self.comboBox_6.addItem("")
        self.comboBox_6.addItem("")
        self.comboBox_6.addItem("")
        self.comboBox_6.addItem("")
        self.comboBox_6.addItem("")
        self.tabWidget.addTab(self.tab_3, "")
        self.tab_4 = QtWidgets.QWidget()
        self.tab_4.setObjectName("tab_4")
        self.label_9 = QtWidgets.QLabel(self.tab_4)
        self.label_9.setGeometry(QtCore.QRect(9, 9, 242, 20))
        self.label_9.setObjectName("label_9")
        self.comboBox_5 = QtWidgets.QComboBox(self.tab_4)
        self.comboBox_5.setGeometry(QtCore.QRect(257, 10, 104, 26))
        self.comboBox_5.setObjectName("comboBox_5")
        self.comboBox_5.addItem("")
        self.pushButton_3 = QtWidgets.QPushButton(self.tab_4)
        self.pushButton_3.setGeometry(QtCore.QRect(367, 9, 118, 28))
        self.pushButton_3.setObjectName("pushButton_3")
        self.tableWidget_4 = QtWidgets.QTableWidget(self.tab_4)
        self.tableWidget_4.setGeometry(QtCore.QRect(9, 43, 471, 441))
        self.tableWidget_4.setObjectName("tableWidget_4")
        self.tableWidget_4.setColumnCount(5)
        self.tableWidget_4.setRowCount(4)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_4.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_4.setVerticalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_4.setVerticalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_4.setVerticalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_4.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_4.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_4.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_4.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_4.setHorizontalHeaderItem(4, item)
        self.label_11 = QtWidgets.QLabel(self.tab_4)
        self.label_11.setGeometry(QtCore.QRect(491, 393, 66, 20))
        self.label_11.setObjectName("label_11")
        self.comboBox_7 = QtWidgets.QComboBox(self.tab_4)
        self.comboBox_7.setGeometry(QtCore.QRect(563, 393, 104, 26))
        self.comboBox_7.setObjectName("comboBox_7")
        self.label_12 = QtWidgets.QLabel(self.tab_4)
        self.label_12.setGeometry(QtCore.QRect(491, 425, 66, 20))
        self.label_12.setObjectName("label_12")
        self.lineEdit_4 = QtWidgets.QLineEdit(self.tab_4)
        self.lineEdit_4.setGeometry(QtCore.QRect(563, 425, 218, 26))
        self.lineEdit_4.setObjectName("lineEdit_4")
        self.label_13 = QtWidgets.QLabel(self.tab_4)
        self.label_13.setGeometry(QtCore.QRect(491, 458, 66, 20))
        self.label_13.setObjectName("label_13")
        self.lineEdit_5 = QtWidgets.QLineEdit(self.tab_4)
        self.lineEdit_5.setGeometry(QtCore.QRect(563, 458, 218, 26))
        self.lineEdit_5.setObjectName("lineEdit_5")
        self.pushButton_6 = QtWidgets.QPushButton(self.tab_4)
        self.pushButton_6.setGeometry(QtCore.QRect(563, 491, 75, 28))
        self.pushButton_6.setObjectName("pushButton_6")
        self.label_14 = QtWidgets.QLabel(self.tab_4)
        self.label_14.setGeometry(QtCore.QRect(520, 170, 66, 27))
        self.label_14.setObjectName("label_14")
        self.lineEdit_6 = QtWidgets.QLineEdit(self.tab_4)
        self.lineEdit_6.setGeometry(QtCore.QRect(610, 180, 290, 27))
        self.lineEdit_6.setObjectName("lineEdit_6")
        self.layoutWidget1 = QtWidgets.QWidget(self.tab_4)
        self.layoutWidget1.setGeometry(QtCore.QRect(530, 220, 292, 63))
        self.layoutWidget1.setObjectName("layoutWidget1")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.layoutWidget1)
        self.gridLayout_3.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.pushButton_5 = QtWidgets.QPushButton(self.layoutWidget1)
        self.pushButton_5.setObjectName("pushButton_5")
        self.gridLayout_3.addWidget(self.pushButton_5, 0, 0, 1, 1)
        self.tableWidget_5 = QtWidgets.QTableWidget(self.tab_4)
        self.tableWidget_5.setGeometry(QtCore.QRect(580, 20, 521, 71))
        self.tableWidget_5.setObjectName("tableWidget_5")
        self.tableWidget_5.setColumnCount(5)
        self.tableWidget_5.setRowCount(1)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_5.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_5.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_5.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_5.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_5.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_5.setHorizontalHeaderItem(4, item)
        self.label_15 = QtWidgets.QLabel(self.tab_4)
        self.label_15.setGeometry(QtCore.QRect(492, 44, 55, 20))
        self.label_15.setObjectName("label_15")
        self.pushButton_4 = QtWidgets.QPushButton(self.tab_4)
        self.pushButton_4.setGeometry(QtCore.QRect(490, 70, 75, 28))
        self.pushButton_4.setObjectName("pushButton_4")
        self.tabWidget.addTab(self.tab_4, "")

        self.retranslateUi(Form)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label.setText(_translate("Form", "CUHKSZ Airline Management System"))
        self.pushButton.setText(_translate("Form", "Search"))
        self.label_2.setText(_translate("Form", "<html><head/><body><p><span style=\" font-size:14pt;\">Flight date:</span></p></body></html>"))
        self.comboBox.setItemText(0, _translate("Form", "Shenzhen (SZX)"))
        self.comboBox.setItemText(1, _translate("Form", "Beijing (PEK)"))
        self.comboBox.setItemText(2, _translate("Form", "Nanchang (KHN)"))
        self.comboBox.setItemText(3, _translate("Form", "Guangdong (CAN)"))
        self.comboBox.setItemText(4, _translate("Form", "Shanghai Pudong (PVG)"))
        self.comboBox.setItemText(5, _translate("Form", "Shanghai Hongqiao (SHA)"))
        self.comboBox.setItemText(6, _translate("Form", "Hangzhou (HGH)"))
        self.label_4.setText(_translate("Form", "To"))
        self.comboBox_2.setItemText(0, _translate("Form", "Beijing (PEK)"))
        self.comboBox_2.setItemText(1, _translate("Form", "Shenzhen (SZX)"))
        self.comboBox_2.setItemText(2, _translate("Form", "Nanchang (KHN)"))
        self.comboBox_2.setItemText(3, _translate("Form", "Guangdong (CAN)"))
        self.comboBox_2.setItemText(4, _translate("Form", "Shanghai Pudong (PVG)"))
        self.comboBox_2.setItemText(5, _translate("Form", "Shanghai Hongqiao (SHA)"))
        self.comboBox_2.setItemText(6, _translate("Form", "Hangzhou (HGH)"))
        self.label_3.setText(_translate("Form", "<html><head/><body><p><span style=\" font-size:14pt;\">From</span></p></body></html>"))
        item = self.tableWidget.verticalHeaderItem(0)
        item.setText(_translate("Form", "1"))
        item = self.tableWidget.verticalHeaderItem(1)
        item.setText(_translate("Form", "2"))
        item = self.tableWidget.verticalHeaderItem(2)
        item.setText(_translate("Form", "3"))
        item = self.tableWidget.verticalHeaderItem(3)
        item.setText(_translate("Form", "4"))
        item = self.tableWidget.verticalHeaderItem(4)
        item.setText(_translate("Form", "5"))
        item = self.tableWidget.verticalHeaderItem(5)
        item.setText(_translate("Form", "6"))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("Form", "Flight Code"))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("Form", "Departure Time"))
        item = self.tableWidget.horizontalHeaderItem(2)
        item.setText(_translate("Form", "Arrivial Time"))
        item = self.tableWidget.horizontalHeaderItem(3)
        item.setText(_translate("Form", "From"))
        item = self.tableWidget.horizontalHeaderItem(4)
        item.setText(_translate("Form", "To"))
        item = self.tableWidget.horizontalHeaderItem(5)
        item.setText(_translate("Form", "Plane Mode"))
        self.planemode.setText(_translate("Form", "Plane Mode"))
        self.label_16.setText(_translate("Form", "Advance Search:"))
        self.planeselect.setItemText(0, _translate("Form", "737-800"))
        self.planeselect.setItemText(1, _translate("Form", "A320"))
        self.planeselect.setItemText(2, _translate("Form", "A321"))
        self.planeselect.setItemText(3, _translate("Form", "737-8"))
        self.directflight.setText(_translate("Form", "Direct flight"))
        self.planeage.setText(_translate("Form", "Plane age < 3"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("Form", "Flight Information"))
        self.label_5.setText(_translate("Form", "Occupation"))
        self.comboBox_3.setItemText(0, _translate("Form", "Cabin Crew"))
        self.comboBox_3.setItemText(1, _translate("Form", "Pilot"))
        self.comboBox_3.setItemText(2, _translate("Form", "Maintainer"))
        self.label_6.setText(_translate("Form", "Level"))
        self.comboBox_4.setItemText(0, _translate("Form", "F1"))
        self.comboBox_4.setItemText(1, _translate("Form", "F2"))
        self.comboBox_4.setItemText(2, _translate("Form", "F3"))
        self.comboBox_4.setItemText(3, _translate("Form", "F4"))
        self.comboBox_4.setItemText(4, _translate("Form", "SF1"))
        self.comboBox_4.setItemText(5, _translate("Form", "SF2"))
        self.comboBox_4.setItemText(6, _translate("Form", "JF1"))
        self.comboBox_4.setItemText(7, _translate("Form", "JF2"))
        self.comboBox_4.setItemText(8, _translate("Form", "SCap"))
        self.comboBox_4.setItemText(9, _translate("Form", "Cap"))
        self.comboBox_4.setItemText(10, _translate("Form", "W1"))
        self.comboBox_4.setItemText(11, _translate("Form", "W2"))
        self.label_7.setText(_translate("Form", "Name (Optional)"))
        self.label_8.setText(_translate("Form", "ID (Optional)"))
        self.lineEdit.setText(_translate("Form", "Li Jiagen"))
        self.lineEdit_2.setText(_translate("Form", "P002"))
        self.pushButton_2.setText(_translate("Form", "Search"))
        item = self.tableWidget_2.verticalHeaderItem(0)
        item.setText(_translate("Form", "1"))
        item = self.tableWidget_2.verticalHeaderItem(1)
        item.setText(_translate("Form", "2"))
        item = self.tableWidget_2.verticalHeaderItem(2)
        item.setText(_translate("Form", "3"))
        item = self.tableWidget_2.verticalHeaderItem(3)
        item.setText(_translate("Form", "4"))
        item = self.tableWidget_2.verticalHeaderItem(4)
        item.setText(_translate("Form", "5"))
        item = self.tableWidget_2.verticalHeaderItem(5)
        item.setText(_translate("Form", "6"))
        item = self.tableWidget_2.horizontalHeaderItem(0)
        item.setText(_translate("Form", "ID"))
        item = self.tableWidget_2.horizontalHeaderItem(1)
        item.setText(_translate("Form", "Name"))
        item = self.tableWidget_2.horizontalHeaderItem(2)
        item.setText(_translate("Form", "Occupation"))
        item = self.tableWidget_2.horizontalHeaderItem(3)
        item.setText(_translate("Form", "Level"))
        item = self.tableWidget_2.horizontalHeaderItem(4)
        item.setText(_translate("Form", "Phone Number"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("Form", "Staff Information"))
        self.label_10.setText(_translate("Form", "Please select a airport:"))
        item = self.tableWidget_3.horizontalHeaderItem(0)
        item.setText(_translate("Form", "IATA"))
        item = self.tableWidget_3.horizontalHeaderItem(1)
        item.setText(_translate("Form", "Full Name"))
        item = self.tableWidget_3.horizontalHeaderItem(2)
        item.setText(_translate("Form", "Flight Zone Grade"))
        item = self.tableWidget_3.horizontalHeaderItem(3)
        item.setText(_translate("Form", "Max Flight Per Day"))
        self.comboBox_6.setItemText(0, _translate("Form", "Shenzhen (SZX)"))
        self.comboBox_6.setItemText(1, _translate("Form", "Beijing (PEK)"))
        self.comboBox_6.setItemText(2, _translate("Form", "Nanchang (KHN)"))
        self.comboBox_6.setItemText(3, _translate("Form", "Guangdong (CAN)"))
        self.comboBox_6.setItemText(4, _translate("Form", "Shanghai Pudong (PVG)"))
        self.comboBox_6.setItemText(5, _translate("Form", "Shanghai Hongqiao (SHA)"))
        self.comboBox_6.setItemText(6, _translate("Form", "Hangzhou (HGH)"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), _translate("Form", "Airport Information"))
        self.label_9.setText(_translate("Form", "Please Select a table:"))
        self.comboBox_5.setItemText(0, _translate("Form", "Pilot"))
        self.pushButton_3.setText(_translate("Form", "Show Table"))
        item = self.tableWidget_4.verticalHeaderItem(0)
        item.setText(_translate("Form", "New Row"))
        item = self.tableWidget_4.verticalHeaderItem(1)
        item.setText(_translate("Form", "New Row"))
        item = self.tableWidget_4.verticalHeaderItem(2)
        item.setText(_translate("Form", "New Row"))
        item = self.tableWidget_4.verticalHeaderItem(3)
        item.setText(_translate("Form", "New Row"))
        item = self.tableWidget_4.horizontalHeaderItem(0)
        item.setText(_translate("Form", "New Column"))
        item = self.tableWidget_4.horizontalHeaderItem(1)
        item.setText(_translate("Form", "New Column"))
        item = self.tableWidget_4.horizontalHeaderItem(2)
        item.setText(_translate("Form", "New Column"))
        item = self.tableWidget_4.horizontalHeaderItem(3)
        item.setText(_translate("Form", "New Column"))
        item = self.tableWidget_4.horizontalHeaderItem(4)
        item.setText(_translate("Form", "New Column"))
        self.label_11.setText(_translate("Form", "Which:"))
        self.label_12.setText(_translate("Form", "Value:"))
        self.label_13.setText(_translate("Form", "Where:"))
        self.pushButton_6.setText(_translate("Form", "Update"))
        self.label_14.setText(_translate("Form", "Where:"))
        self.pushButton_5.setText(_translate("Form", "Delete"))
        item = self.tableWidget_5.verticalHeaderItem(0)
        item.setText(_translate("Form", "Insert"))
        item = self.tableWidget_5.horizontalHeaderItem(0)
        item.setText(_translate("Form", "New Column"))
        item = self.tableWidget_5.horizontalHeaderItem(1)
        item.setText(_translate("Form", "New Column"))
        item = self.tableWidget_5.horizontalHeaderItem(2)
        item.setText(_translate("Form", "New Column"))
        item = self.tableWidget_5.horizontalHeaderItem(3)
        item.setText(_translate("Form", "New Column"))
        item = self.tableWidget_5.horizontalHeaderItem(4)
        item.setText(_translate("Form", "New Column"))
        self.label_15.setText(_translate("Form", "What:"))
        self.pushButton_4.setText(_translate("Form", "Insert"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_4), _translate("Form", "Information Management"))

