# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'database_project.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(1171, 731)
        self.label = QtWidgets.QLabel(Form)
        self.label.setGeometry(QtCore.QRect(10, 4, 491, 41))
        font = QtGui.QFont()
        font.setFamily("3ds")
        font.setPointSize(20)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.tabWidget = QtWidgets.QTabWidget(Form)
        self.tabWidget.setGeometry(QtCore.QRect(10, 50, 1151, 671))
        font = QtGui.QFont()
        font.setFamily("3ds")
        font.setPointSize(14)
        font.setBold(False)
        font.setWeight(50)
        self.tabWidget.setFont(font)
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.searchFlight = QtWidgets.QPushButton(self.tab)
        self.searchFlight.setGeometry(QtCore.QRect(260, 390, 101, 51))
        self.searchFlight.setObjectName("searchFlight")
        self.layoutWidget = QtWidgets.QWidget(self.tab)
        self.layoutWidget.setGeometry(QtCore.QRect(10, 20, 351, 141))
        self.layoutWidget.setObjectName("layoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.layoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.label_2 = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(13)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 0, 0, 1, 1)
        self.dateEdit = QtWidgets.QDateEdit(self.layoutWidget)
        self.dateEdit.setDateTime(QtCore.QDateTime(QtCore.QDate(2019, 4, 22), QtCore.QTime(0, 0, 0)))
        self.dateEdit.setMaximumDateTime(QtCore.QDateTime(QtCore.QDate(2019, 6, 30), QtCore.QTime(0, 0, 0)))
        self.dateEdit.setMinimumDateTime(QtCore.QDateTime(QtCore.QDate(2019, 3, 15), QtCore.QTime(0, 0, 0)))
        self.dateEdit.setMaximumDate(QtCore.QDate(2019, 6, 30))
        self.dateEdit.setCalendarPopup(True)
        self.dateEdit.setObjectName("dateEdit")
        self.gridLayout.addWidget(self.dateEdit, 0, 1, 1, 1)
        self.comboBox = QtWidgets.QComboBox(self.layoutWidget)
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.gridLayout.addWidget(self.comboBox, 1, 1, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.layoutWidget)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 2, 0, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(13)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 1, 0, 1, 1)
        self.comboBox_2 = QtWidgets.QComboBox(self.layoutWidget)
        self.comboBox_2.setObjectName("comboBox_2")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.gridLayout.addWidget(self.comboBox_2, 2, 1, 1, 1)
        self.tableWidget = QtWidgets.QTableWidget(self.tab)
        self.tableWidget.setGeometry(QtCore.QRect(380, 20, 761, 601))
        font = QtGui.QFont()
        font.setFamily("3ds")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.tableWidget.setFont(font)
        self.tableWidget.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(6)
        self.tableWidget.setRowCount(18)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(7, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(8, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(9, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(10, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(11, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(12, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(13, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(14, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(15, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(16, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(17, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(5, item)
        self.tableWidget.horizontalHeader().setDefaultSectionSize(121)
        self.planemode = QtWidgets.QCheckBox(self.tab)
        self.planemode.setGeometry(QtCore.QRect(12, 212, 110, 21))
        font = QtGui.QFont()
        font.setFamily("3ds")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.planemode.setFont(font)
        self.planemode.setObjectName("planemode")
        self.label_16 = QtWidgets.QLabel(self.tab)
        self.label_16.setGeometry(QtCore.QRect(11, 176, 151, 20))
        font = QtGui.QFont()
        font.setFamily("3ds")
        font.setPointSize(14)
        font.setBold(False)
        font.setWeight(50)
        self.label_16.setFont(font)
        self.label_16.setObjectName("label_16")
        self.planeselect = QtWidgets.QComboBox(self.tab)
        self.planeselect.setGeometry(QtCore.QRect(130, 207, 151, 30))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.planeselect.setFont(font)
        self.planeselect.setObjectName("planeselect")
        self.planeselect.addItem("")
        self.planeselect.addItem("")
        self.planeselect.addItem("")
        self.planeselect.addItem("")
        self.directflight = QtWidgets.QCheckBox(self.tab)
        self.directflight.setGeometry(QtCore.QRect(12, 256, 111, 21))
        font = QtGui.QFont()
        font.setFamily("3ds")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.directflight.setFont(font)
        self.directflight.setObjectName("directflight")
        self.planeage = QtWidgets.QCheckBox(self.tab)
        self.planeage.setGeometry(QtCore.QRect(12, 299, 131, 20))
        font = QtGui.QFont()
        font.setFamily("3ds")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.planeage.setFont(font)
        self.planeage.setObjectName("planeage")
        self.passenger = QtWidgets.QCheckBox(self.tab)
        self.passenger.setGeometry(QtCore.QRect(12, 341, 131, 20))
        font = QtGui.QFont()
        font.setFamily("3ds")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.passenger.setFont(font)
        self.passenger.setObjectName("passenger")
        self.passengernum = QtWidgets.QLineEdit(self.tab)
        self.passengernum.setGeometry(QtCore.QRect(131, 336, 131, 31))
        self.passengernum.setObjectName("passengernum")
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.tableWidget_2 = QtWidgets.QTableWidget(self.tab_2)
        self.tableWidget_2.setGeometry(QtCore.QRect(380, 20, 761, 601))
        self.tableWidget_2.setBaseSize(QtCore.QSize(100, 0))
        font = QtGui.QFont()
        font.setFamily("3ds")
        font.setPointSize(12)
        self.tableWidget_2.setFont(font)
        self.tableWidget_2.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.tableWidget_2.setObjectName("tableWidget_2")
        self.tableWidget_2.setColumnCount(6)
        self.tableWidget_2.setRowCount(19)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setVerticalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setVerticalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setVerticalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setVerticalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setVerticalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setVerticalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setVerticalHeaderItem(7, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setVerticalHeaderItem(8, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setVerticalHeaderItem(9, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setVerticalHeaderItem(10, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setVerticalHeaderItem(11, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setVerticalHeaderItem(12, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setVerticalHeaderItem(13, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setVerticalHeaderItem(14, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setVerticalHeaderItem(15, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setVerticalHeaderItem(16, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setVerticalHeaderItem(17, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setVerticalHeaderItem(18, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(5, item)
        self.tableWidget_2.horizontalHeader().setDefaultSectionSize(119)
        self.searchStaff = QtWidgets.QPushButton(self.tab_2)
        self.searchStaff.setGeometry(QtCore.QRect(260, 170, 101, 51))
        self.searchStaff.setObjectName("searchStaff")
        self.gridLayoutWidget_2 = QtWidgets.QWidget(self.tab_2)
        self.gridLayoutWidget_2.setGeometry(QtCore.QRect(10, 20, 351, 136))
        self.gridLayoutWidget_2.setObjectName("gridLayoutWidget_2")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.gridLayoutWidget_2)
        self.gridLayout_4.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.label_5 = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.label_5.setObjectName("label_5")
        self.gridLayout_4.addWidget(self.label_5, 0, 0, 1, 1)
        self.comboBox_4 = QtWidgets.QComboBox(self.gridLayoutWidget_2)
        self.comboBox_4.setObjectName("comboBox_4")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.gridLayout_4.addWidget(self.comboBox_4, 1, 1, 1, 1)
        self.comboBox_3 = QtWidgets.QComboBox(self.gridLayoutWidget_2)
        self.comboBox_3.setObjectName("comboBox_3")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.gridLayout_4.addWidget(self.comboBox_3, 0, 1, 1, 1)
        self.label_7 = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.label_7.setObjectName("label_7")
        self.gridLayout_4.addWidget(self.label_7, 2, 0, 1, 1)
        self.label_6 = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.label_6.setObjectName("label_6")
        self.gridLayout_4.addWidget(self.label_6, 1, 0, 1, 1)
        self.lineEdit = QtWidgets.QLineEdit(self.gridLayoutWidget_2)
        self.lineEdit.setText("")
        self.lineEdit.setObjectName("lineEdit")
        self.gridLayout_4.addWidget(self.lineEdit, 2, 1, 1, 1)
        self.label_8 = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.label_8.setObjectName("label_8")
        self.gridLayout_4.addWidget(self.label_8, 3, 0, 1, 1)
        self.lineEdit_2 = QtWidgets.QLineEdit(self.gridLayoutWidget_2)
        self.lineEdit_2.setText("")
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.gridLayout_4.addWidget(self.lineEdit_2, 3, 1, 1, 1)
        self.tabWidget.addTab(self.tab_2, "")
        self.tab_4 = QtWidgets.QWidget()
        self.tab_4.setObjectName("tab_4")
        self.planeTable = QtWidgets.QTableWidget(self.tab_4)
        self.planeTable.setGeometry(QtCore.QRect(380, 20, 761, 601))
        self.planeTable.setBaseSize(QtCore.QSize(100, 0))
        font = QtGui.QFont()
        font.setFamily("3ds")
        font.setPointSize(12)
        self.planeTable.setFont(font)
        self.planeTable.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.planeTable.setObjectName("planeTable")
        self.planeTable.setColumnCount(6)
        self.planeTable.setRowCount(19)
        item = QtWidgets.QTableWidgetItem()
        self.planeTable.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.planeTable.setVerticalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.planeTable.setVerticalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.planeTable.setVerticalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.planeTable.setVerticalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.planeTable.setVerticalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.planeTable.setVerticalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        self.planeTable.setVerticalHeaderItem(7, item)
        item = QtWidgets.QTableWidgetItem()
        self.planeTable.setVerticalHeaderItem(8, item)
        item = QtWidgets.QTableWidgetItem()
        self.planeTable.setVerticalHeaderItem(9, item)
        item = QtWidgets.QTableWidgetItem()
        self.planeTable.setVerticalHeaderItem(10, item)
        item = QtWidgets.QTableWidgetItem()
        self.planeTable.setVerticalHeaderItem(11, item)
        item = QtWidgets.QTableWidgetItem()
        self.planeTable.setVerticalHeaderItem(12, item)
        item = QtWidgets.QTableWidgetItem()
        self.planeTable.setVerticalHeaderItem(13, item)
        item = QtWidgets.QTableWidgetItem()
        self.planeTable.setVerticalHeaderItem(14, item)
        item = QtWidgets.QTableWidgetItem()
        self.planeTable.setVerticalHeaderItem(15, item)
        item = QtWidgets.QTableWidgetItem()
        self.planeTable.setVerticalHeaderItem(16, item)
        item = QtWidgets.QTableWidgetItem()
        self.planeTable.setVerticalHeaderItem(17, item)
        item = QtWidgets.QTableWidgetItem()
        self.planeTable.setVerticalHeaderItem(18, item)
        item = QtWidgets.QTableWidgetItem()
        self.planeTable.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.planeTable.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.planeTable.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.planeTable.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.planeTable.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.planeTable.setHorizontalHeaderItem(5, item)
        self.planeTable.horizontalHeader().setDefaultSectionSize(119)
        self.gridLayoutWidget_3 = QtWidgets.QWidget(self.tab_4)
        self.gridLayoutWidget_3.setGeometry(QtCore.QRect(10, 20, 351, 80))
        self.gridLayoutWidget_3.setObjectName("gridLayoutWidget_3")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.gridLayoutWidget_3)
        self.gridLayout_3.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.label_9 = QtWidgets.QLabel(self.gridLayoutWidget_3)
        self.label_9.setAlignment(QtCore.Qt.AlignCenter)
        self.label_9.setObjectName("label_9")
        self.gridLayout_3.addWidget(self.label_9, 0, 0, 1, 1)
        self.planeRegNum = QtWidgets.QComboBox(self.gridLayoutWidget_3)
        self.planeRegNum.setObjectName("planeRegNum")
        self.planeRegNum.addItem("")
        self.planeRegNum.setItemText(0, "")
        self.planeRegNum.addItem("")
        self.planeRegNum.addItem("")
        self.planeRegNum.addItem("")
        self.planeRegNum.addItem("")
        self.planeRegNum.addItem("")
        self.planeRegNum.addItem("")
        self.planeRegNum.addItem("")
        self.planeRegNum.addItem("")
        self.gridLayout_3.addWidget(self.planeRegNum, 1, 0, 1, 1)
        self.planeAge = QtWidgets.QLineEdit(self.gridLayoutWidget_3)
        self.planeAge.setObjectName("planeAge")
        self.gridLayout_3.addWidget(self.planeAge, 1, 1, 1, 1)
        self.label_11 = QtWidgets.QLabel(self.gridLayoutWidget_3)
        self.label_11.setAlignment(QtCore.Qt.AlignCenter)
        self.label_11.setObjectName("label_11")
        self.gridLayout_3.addWidget(self.label_11, 0, 1, 1, 1)
        self.label_12 = QtWidgets.QLabel(self.gridLayoutWidget_3)
        self.label_12.setAlignment(QtCore.Qt.AlignCenter)
        self.label_12.setObjectName("label_12")
        self.gridLayout_3.addWidget(self.label_12, 0, 2, 1, 1)
        self.planeModelID = QtWidgets.QComboBox(self.gridLayoutWidget_3)
        self.planeModelID.setObjectName("planeModelID")
        self.planeModelID.addItem("")
        self.planeModelID.setItemText(0, "")
        self.planeModelID.addItem("")
        self.planeModelID.addItem("")
        self.gridLayout_3.addWidget(self.planeModelID, 1, 2, 1, 1)
        self.searchPlane = QtWidgets.QPushButton(self.tab_4)
        self.searchPlane.setGeometry(QtCore.QRect(260, 120, 101, 51))
        self.searchPlane.setObjectName("searchPlane")
        self.tabWidget.addTab(self.tab_4, "")
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.label_10 = QtWidgets.QLabel(self.tab_3)
        self.label_10.setGeometry(QtCore.QRect(20, 10, 271, 41))
        self.label_10.setObjectName("label_10")
        self.tableWidget_3 = QtWidgets.QTableWidget(self.tab_3)
        self.tableWidget_3.setGeometry(QtCore.QRect(0, 60, 1141, 481))
        self.tableWidget_3.setMinimumSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setFamily("3ds")
        font.setPointSize(12)
        self.tableWidget_3.setFont(font)
        self.tableWidget_3.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.tableWidget_3.setIconSize(QtCore.QSize(200, 200))
        self.tableWidget_3.setRowCount(10)
        self.tableWidget_3.setObjectName("tableWidget_3")
        self.tableWidget_3.setColumnCount(4)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_3.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_3.setVerticalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_3.setVerticalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_3.setVerticalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_3.setVerticalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_3.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_3.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_3.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_3.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_3.setItem(0, 2, item)
        self.tableWidget_3.horizontalHeader().setCascadingSectionResizes(False)
        self.tableWidget_3.horizontalHeader().setDefaultSectionSize(277)
        self.tableWidget_3.horizontalHeader().setSortIndicatorShown(False)
        self.tableWidget_3.horizontalHeader().setStretchLastSection(False)
        self.tableWidget_3.verticalHeader().setCascadingSectionResizes(False)
        self.tableWidget_3.verticalHeader().setDefaultSectionSize(45)
        self.comboBox_6 = QtWidgets.QComboBox(self.tab_3)
        self.comboBox_6.setGeometry(QtCore.QRect(300, 20, 276, 26))
        self.comboBox_6.setObjectName("comboBox_6")
        self.comboBox_6.addItem("")
        self.comboBox_6.addItem("")
        self.comboBox_6.addItem("")
        self.comboBox_6.addItem("")
        self.comboBox_6.addItem("")
        self.comboBox_6.addItem("")
        self.comboBox_6.addItem("")
        self.comboBox_6.addItem("")
        self.searchAirport = QtWidgets.QPushButton(self.tab_3)
        self.searchAirport.setGeometry(QtCore.QRect(1020, 560, 121, 51))
        self.searchAirport.setObjectName("searchAirport")
        self.tabWidget.addTab(self.tab_3, "")
        self.tab_5 = QtWidgets.QWidget()
        self.tab_5.setObjectName("tab_5")
        self.gridLayoutWidget = QtWidgets.QWidget(self.tab_5)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(0, 420, 1141, 151))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout_2.setSizeConstraint(QtWidgets.QLayout.SetNoConstraint)
        self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.newRegNum = QtWidgets.QComboBox(self.gridLayoutWidget)
        self.newRegNum.setObjectName("newRegNum")
        self.newRegNum.addItem("")
        self.newRegNum.addItem("")
        self.newRegNum.addItem("")
        self.newRegNum.addItem("")
        self.newRegNum.addItem("")
        self.newRegNum.addItem("")
        self.newRegNum.addItem("")
        self.newRegNum.addItem("")
        self.gridLayout_2.addWidget(self.newRegNum, 4, 3, 1, 1)
        self.label_23 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_23.setAlignment(QtCore.Qt.AlignCenter)
        self.label_23.setObjectName("label_23")
        self.gridLayout_2.addWidget(self.label_23, 3, 4, 1, 1)
        self.label_25 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_25.setAlignment(QtCore.Qt.AlignCenter)
        self.label_25.setObjectName("label_25")
        self.gridLayout_2.addWidget(self.label_25, 3, 5, 1, 1)
        self.label_26 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_26.setAlignment(QtCore.Qt.AlignCenter)
        self.label_26.setObjectName("label_26")
        self.gridLayout_2.addWidget(self.label_26, 3, 2, 1, 1)
        self.newPilotID = QtWidgets.QComboBox(self.gridLayoutWidget)
        self.newPilotID.setObjectName("newPilotID")
        self.newPilotID.addItem("")
        self.newPilotID.addItem("")
        self.newPilotID.addItem("")
        self.newPilotID.addItem("")
        self.newPilotID.addItem("")
        self.newPilotID.addItem("")
        self.newPilotID.addItem("")
        self.newPilotID.addItem("")
        self.gridLayout_2.addWidget(self.newPilotID, 4, 4, 1, 1)
        self.label_19 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_19.setAlignment(QtCore.Qt.AlignCenter)
        self.label_19.setObjectName("label_19")
        self.gridLayout_2.addWidget(self.label_19, 5, 0, 1, 1)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_28 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_28.setObjectName("label_28")
        self.horizontalLayout_3.addWidget(self.label_28)
        self.newFlightCode = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.newFlightCode.setObjectName("newFlightCode")
        self.horizontalLayout_3.addWidget(self.newFlightCode)
        self.gridLayout_2.addLayout(self.horizontalLayout_3, 4, 2, 1, 1)
        self.label_17 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_17.setAlignment(QtCore.Qt.AlignCenter)
        self.label_17.setObjectName("label_17")
        self.gridLayout_2.addWidget(self.label_17, 3, 3, 1, 1)
        self.newPassengerNum = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.newPassengerNum.setObjectName("newPassengerNum")
        self.gridLayout_2.addWidget(self.newPassengerNum, 4, 5, 1, 1)
        self.label_27 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_27.setAlignment(QtCore.Qt.AlignCenter)
        self.label_27.setObjectName("label_27")
        self.gridLayout_2.addWidget(self.label_27, 3, 0, 1, 1)
        self.newDate = QtWidgets.QDateEdit(self.gridLayoutWidget)
        self.newDate.setDateTime(QtCore.QDateTime(QtCore.QDate(2019, 4, 29), QtCore.QTime(0, 0, 0)))
        self.newDate.setMaximumDateTime(QtCore.QDateTime(QtCore.QDate(2019, 6, 30), QtCore.QTime(0, 0, 0)))
        self.newDate.setMinimumDateTime(QtCore.QDateTime(QtCore.QDate(2019, 3, 1), QtCore.QTime(0, 0, 0)))
        self.newDate.setObjectName("newDate")
        self.gridLayout_2.addWidget(self.newDate, 4, 0, 1, 1)
        self.newDepTime = QtWidgets.QTimeEdit(self.gridLayoutWidget)
        self.newDepTime.setDateTime(QtCore.QDateTime(QtCore.QDate(2000, 1, 1), QtCore.QTime(9, 0, 0)))
        self.newDepTime.setObjectName("newDepTime")
        self.gridLayout_2.addWidget(self.newDepTime, 6, 0, 1, 1)
        self.label_21 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_21.setAlignment(QtCore.Qt.AlignCenter)
        self.label_21.setObjectName("label_21")
        self.gridLayout_2.addWidget(self.label_21, 5, 2, 1, 1)
        self.label_22 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_22.setAlignment(QtCore.Qt.AlignCenter)
        self.label_22.setObjectName("label_22")
        self.gridLayout_2.addWidget(self.label_22, 5, 3, 1, 1)
        self.newArrTime = QtWidgets.QTimeEdit(self.gridLayoutWidget)
        self.newArrTime.setDateTime(QtCore.QDateTime(QtCore.QDate(2000, 1, 1), QtCore.QTime(12, 0, 0)))
        self.newArrTime.setObjectName("newArrTime")
        self.gridLayout_2.addWidget(self.newArrTime, 6, 3, 1, 1)
        self.label_20 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_20.setAlignment(QtCore.Qt.AlignCenter)
        self.label_20.setObjectName("label_20")
        self.gridLayout_2.addWidget(self.label_20, 5, 4, 1, 1)
        self.label_24 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_24.setAlignment(QtCore.Qt.AlignCenter)
        self.label_24.setObjectName("label_24")
        self.gridLayout_2.addWidget(self.label_24, 5, 5, 1, 1)
        self.newDepFCCCode = QtWidgets.QComboBox(self.gridLayoutWidget)
        self.newDepFCCCode.setObjectName("newDepFCCCode")
        self.newDepFCCCode.addItem("")
        self.newDepFCCCode.addItem("")
        self.newDepFCCCode.addItem("")
        self.newDepFCCCode.addItem("")
        self.newDepFCCCode.addItem("")
        self.newDepFCCCode.addItem("")
        self.newDepFCCCode.addItem("")
        self.newDepFCCCode.addItem("")
        self.newDepFCCCode.addItem("")
        self.newDepFCCCode.addItem("")
        self.gridLayout_2.addWidget(self.newDepFCCCode, 6, 2, 1, 1)
        self.newArrFCCCode = QtWidgets.QComboBox(self.gridLayoutWidget)
        self.newArrFCCCode.setObjectName("newArrFCCCode")
        self.newArrFCCCode.addItem("")
        self.newArrFCCCode.addItem("")
        self.newArrFCCCode.addItem("")
        self.newArrFCCCode.addItem("")
        self.newArrFCCCode.addItem("")
        self.newArrFCCCode.addItem("")
        self.newArrFCCCode.addItem("")
        self.newArrFCCCode.addItem("")
        self.newArrFCCCode.addItem("")
        self.newArrFCCCode.addItem("")
        self.gridLayout_2.addWidget(self.newArrFCCCode, 6, 4, 1, 1)
        self.newStpFCCCode = QtWidgets.QComboBox(self.gridLayoutWidget)
        self.newStpFCCCode.setObjectName("newStpFCCCode")
        self.newStpFCCCode.addItem("")
        self.newStpFCCCode.setItemText(0, "")
        self.newStpFCCCode.addItem("")
        self.newStpFCCCode.addItem("")
        self.newStpFCCCode.addItem("")
        self.newStpFCCCode.addItem("")
        self.newStpFCCCode.addItem("")
        self.newStpFCCCode.addItem("")
        self.newStpFCCCode.addItem("")
        self.newStpFCCCode.addItem("")
        self.newStpFCCCode.addItem("")
        self.newStpFCCCode.addItem("")
        self.gridLayout_2.addWidget(self.newStpFCCCode, 6, 5, 1, 1)
        self.tableWidget_6 = QtWidgets.QTableWidget(self.tab_5)
        self.tableWidget_6.setGeometry(QtCore.QRect(0, 0, 1141, 341))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tableWidget_6.sizePolicy().hasHeightForWidth())
        self.tableWidget_6.setSizePolicy(sizePolicy)
        self.tableWidget_6.setBaseSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setFamily("3ds")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.tableWidget_6.setFont(font)
        self.tableWidget_6.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.tableWidget_6.setSelectionMode(QtWidgets.QAbstractItemView.SingleSelection)
        self.tableWidget_6.setRowCount(100)
        self.tableWidget_6.setObjectName("tableWidget_6")
        self.tableWidget_6.setColumnCount(10)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignVCenter)
        self.tableWidget_6.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_6.setVerticalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_6.setVerticalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_6.setVerticalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_6.setVerticalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_6.setVerticalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_6.setVerticalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_6.setVerticalHeaderItem(7, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_6.setVerticalHeaderItem(8, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_6.setVerticalHeaderItem(9, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_6.setVerticalHeaderItem(10, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_6.setVerticalHeaderItem(11, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_6.setVerticalHeaderItem(12, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.tableWidget_6.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_6.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_6.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_6.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_6.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_6.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_6.setHorizontalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_6.setHorizontalHeaderItem(7, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_6.setHorizontalHeaderItem(8, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_6.setHorizontalHeaderItem(9, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.tableWidget_6.setItem(5, 9, item)
        self.tableWidget_6.horizontalHeader().setDefaultSectionSize(109)
        self.insertFlight = QtWidgets.QPushButton(self.tab_5)
        self.insertFlight.setGeometry(QtCore.QRect(1040, 580, 101, 51))
        self.insertFlight.setObjectName("insertFlight")
        self.deleteFlight = QtWidgets.QPushButton(self.tab_5)
        self.deleteFlight.setGeometry(QtCore.QRect(1040, 350, 101, 51))
        self.deleteFlight.setObjectName("deleteFlight")
        self.tabWidget.addTab(self.tab_5, "")

        self.retranslateUi(Form)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "LGU Airlines"))
        self.label.setText(_translate("Form", "CUHKSZ Airline Management System"))
        self.searchFlight.setText(_translate("Form", "Search"))
        self.label_2.setText(_translate("Form", "<html><head/><body><p><span style=\" font-size:14pt;\">Flight date:</span></p></body></html>"))
        self.comboBox.setItemText(0, _translate("Form", "Wherever"))
        self.comboBox.setItemText(1, _translate("Form", "Shenzhen (SZX)"))
        self.comboBox.setItemText(2, _translate("Form", "Beijing (PEK)"))
        self.comboBox.setItemText(3, _translate("Form", "Nanchang (KHN)"))
        self.comboBox.setItemText(4, _translate("Form", "Chengdu (CTU)"))
        self.comboBox.setItemText(5, _translate("Form", "Guangzhou (CAN)"))
        self.comboBox.setItemText(6, _translate("Form", "Hangzhou (HGH)"))
        self.comboBox.setItemText(7, _translate("Form", "Wuhan (WUH)"))
        self.comboBox.setItemText(8, _translate("Form", "Shanghai Pudong (PVG)"))
        self.comboBox.setItemText(9, _translate("Form", "Shanghai Hongqiao (SHA)"))
        self.comboBox.setItemText(10, _translate("Form", "Xi\'an (XIY)"))
        self.label_4.setText(_translate("Form", "To"))
        self.label_3.setText(_translate("Form", "<html><head/><body><p><span style=\" font-size:14pt;\">From</span></p></body></html>"))
        self.comboBox_2.setItemText(0, _translate("Form", "Wherever"))
        self.comboBox_2.setItemText(1, _translate("Form", "Shenzhen (SZX)"))
        self.comboBox_2.setItemText(2, _translate("Form", "Beijing (PEK)"))
        self.comboBox_2.setItemText(3, _translate("Form", "Nanchang (KHN)"))
        self.comboBox_2.setItemText(4, _translate("Form", "Chengdu (CTU)"))
        self.comboBox_2.setItemText(5, _translate("Form", "Guangzhou (CAN)"))
        self.comboBox_2.setItemText(6, _translate("Form", "Hangzhou (HGH)"))
        self.comboBox_2.setItemText(7, _translate("Form", "Wuhan (WUH)"))
        self.comboBox_2.setItemText(8, _translate("Form", "Shanghai Pudong (PVG)"))
        self.comboBox_2.setItemText(9, _translate("Form", "Shanghai Hongqiao (SHA)"))
        self.comboBox_2.setItemText(10, _translate("Form", "Xi\'an (XIY)"))
        item = self.tableWidget.verticalHeaderItem(0)
        item.setText(_translate("Form", "1"))
        item = self.tableWidget.verticalHeaderItem(1)
        item.setText(_translate("Form", "2"))
        item = self.tableWidget.verticalHeaderItem(2)
        item.setText(_translate("Form", "3"))
        item = self.tableWidget.verticalHeaderItem(3)
        item.setText(_translate("Form", "4"))
        item = self.tableWidget.verticalHeaderItem(4)
        item.setText(_translate("Form", "5"))
        item = self.tableWidget.verticalHeaderItem(5)
        item.setText(_translate("Form", "6"))
        item = self.tableWidget.verticalHeaderItem(6)
        item.setText(_translate("Form", "7"))
        item = self.tableWidget.verticalHeaderItem(7)
        item.setText(_translate("Form", "8"))
        item = self.tableWidget.verticalHeaderItem(8)
        item.setText(_translate("Form", "9"))
        item = self.tableWidget.verticalHeaderItem(9)
        item.setText(_translate("Form", "10"))
        item = self.tableWidget.verticalHeaderItem(10)
        item.setText(_translate("Form", "11"))
        item = self.tableWidget.verticalHeaderItem(11)
        item.setText(_translate("Form", "12"))
        item = self.tableWidget.verticalHeaderItem(12)
        item.setText(_translate("Form", "13"))
        item = self.tableWidget.verticalHeaderItem(13)
        item.setText(_translate("Form", "14"))
        item = self.tableWidget.verticalHeaderItem(14)
        item.setText(_translate("Form", "15"))
        item = self.tableWidget.verticalHeaderItem(15)
        item.setText(_translate("Form", "16"))
        item = self.tableWidget.verticalHeaderItem(16)
        item.setText(_translate("Form", "17"))
        item = self.tableWidget.verticalHeaderItem(17)
        item.setText(_translate("Form", "18"))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("Form", "Flight Code"))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("Form", "Dep. Time"))
        item = self.tableWidget.horizontalHeaderItem(2)
        item.setText(_translate("Form", "Arr. Time"))
        item = self.tableWidget.horizontalHeaderItem(3)
        item.setText(_translate("Form", "From"))
        item = self.tableWidget.horizontalHeaderItem(4)
        item.setText(_translate("Form", "To"))
        item = self.tableWidget.horizontalHeaderItem(5)
        item.setText(_translate("Form", "Plane Mode"))
        self.planemode.setText(_translate("Form", "Plane Mode"))
        self.label_16.setText(_translate("Form", "Advance Search:"))
        self.planeselect.setItemText(0, _translate("Form", "737-800"))
        self.planeselect.setItemText(1, _translate("Form", "A320"))
        self.planeselect.setItemText(2, _translate("Form", "A321"))
        self.planeselect.setItemText(3, _translate("Form", "737-8"))
        self.directflight.setText(_translate("Form", "Direct flight"))
        self.planeage.setText(_translate("Form", "Plane age <= 3"))
        self.passenger.setText(_translate("Form", "Passanger < "))
        self.passengernum.setText(_translate("Form", "180"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("Form", "Flight Information"))
        item = self.tableWidget_2.verticalHeaderItem(0)
        item.setText(_translate("Form", "1"))
        item = self.tableWidget_2.verticalHeaderItem(1)
        item.setText(_translate("Form", "2"))
        item = self.tableWidget_2.verticalHeaderItem(2)
        item.setText(_translate("Form", "3"))
        item = self.tableWidget_2.verticalHeaderItem(3)
        item.setText(_translate("Form", "4"))
        item = self.tableWidget_2.verticalHeaderItem(4)
        item.setText(_translate("Form", "5"))
        item = self.tableWidget_2.verticalHeaderItem(5)
        item.setText(_translate("Form", "6"))
        item = self.tableWidget_2.verticalHeaderItem(6)
        item.setText(_translate("Form", "7"))
        item = self.tableWidget_2.verticalHeaderItem(7)
        item.setText(_translate("Form", "8"))
        item = self.tableWidget_2.verticalHeaderItem(8)
        item.setText(_translate("Form", "10"))
        item = self.tableWidget_2.verticalHeaderItem(9)
        item.setText(_translate("Form", "11"))
        item = self.tableWidget_2.verticalHeaderItem(10)
        item.setText(_translate("Form", "12"))
        item = self.tableWidget_2.verticalHeaderItem(11)
        item.setText(_translate("Form", "13"))
        item = self.tableWidget_2.verticalHeaderItem(12)
        item.setText(_translate("Form", "14"))
        item = self.tableWidget_2.verticalHeaderItem(13)
        item.setText(_translate("Form", "15"))
        item = self.tableWidget_2.verticalHeaderItem(14)
        item.setText(_translate("Form", "16"))
        item = self.tableWidget_2.verticalHeaderItem(15)
        item.setText(_translate("Form", "17"))
        item = self.tableWidget_2.verticalHeaderItem(16)
        item.setText(_translate("Form", "18"))
        item = self.tableWidget_2.verticalHeaderItem(17)
        item.setText(_translate("Form", "19"))
        item = self.tableWidget_2.verticalHeaderItem(18)
        item.setText(_translate("Form", "20"))
        item = self.tableWidget_2.horizontalHeaderItem(0)
        item.setText(_translate("Form", "ID"))
        item = self.tableWidget_2.horizontalHeaderItem(1)
        item.setText(_translate("Form", "First Name"))
        item = self.tableWidget_2.horizontalHeaderItem(2)
        item.setText(_translate("Form", "Last Name"))
        item = self.tableWidget_2.horizontalHeaderItem(3)
        item.setText(_translate("Form", "Level"))
        item = self.tableWidget_2.horizontalHeaderItem(4)
        item.setText(_translate("Form", "Phone Number"))
        item = self.tableWidget_2.horizontalHeaderItem(5)
        item.setText(_translate("Form", "Salary"))
        self.searchStaff.setText(_translate("Form", "Search"))
        self.label_5.setText(_translate("Form", "Occupation"))
        self.comboBox_4.setItemText(0, _translate("Form", "F1"))
        self.comboBox_4.setItemText(1, _translate("Form", "F2"))
        self.comboBox_4.setItemText(2, _translate("Form", "F3"))
        self.comboBox_4.setItemText(3, _translate("Form", "F4"))
        self.comboBox_3.setItemText(0, _translate("Form", "Cabin Crew"))
        self.comboBox_3.setItemText(1, _translate("Form", "Pilot"))
        self.comboBox_3.setItemText(2, _translate("Form", "Maintainer"))
        self.label_7.setText(_translate("Form", "First Name (Optional)"))
        self.label_6.setText(_translate("Form", "Level"))
        self.label_8.setText(_translate("Form", "ID (Optional)"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("Form", "Staff Information"))
        item = self.planeTable.verticalHeaderItem(0)
        item.setText(_translate("Form", "1"))
        item = self.planeTable.verticalHeaderItem(1)
        item.setText(_translate("Form", "2"))
        item = self.planeTable.verticalHeaderItem(2)
        item.setText(_translate("Form", "3"))
        item = self.planeTable.verticalHeaderItem(3)
        item.setText(_translate("Form", "4"))
        item = self.planeTable.verticalHeaderItem(4)
        item.setText(_translate("Form", "5"))
        item = self.planeTable.verticalHeaderItem(5)
        item.setText(_translate("Form", "6"))
        item = self.planeTable.verticalHeaderItem(6)
        item.setText(_translate("Form", "7"))
        item = self.planeTable.verticalHeaderItem(7)
        item.setText(_translate("Form", "8"))
        item = self.planeTable.verticalHeaderItem(8)
        item.setText(_translate("Form", "10"))
        item = self.planeTable.verticalHeaderItem(9)
        item.setText(_translate("Form", "11"))
        item = self.planeTable.verticalHeaderItem(10)
        item.setText(_translate("Form", "12"))
        item = self.planeTable.verticalHeaderItem(11)
        item.setText(_translate("Form", "13"))
        item = self.planeTable.verticalHeaderItem(12)
        item.setText(_translate("Form", "14"))
        item = self.planeTable.verticalHeaderItem(13)
        item.setText(_translate("Form", "15"))
        item = self.planeTable.verticalHeaderItem(14)
        item.setText(_translate("Form", "16"))
        item = self.planeTable.verticalHeaderItem(15)
        item.setText(_translate("Form", "17"))
        item = self.planeTable.verticalHeaderItem(16)
        item.setText(_translate("Form", "18"))
        item = self.planeTable.verticalHeaderItem(17)
        item.setText(_translate("Form", "19"))
        item = self.planeTable.verticalHeaderItem(18)
        item.setText(_translate("Form", "20"))
        item = self.planeTable.horizontalHeaderItem(0)
        item.setText(_translate("Form", "Reg. Num."))
        item = self.planeTable.horizontalHeaderItem(1)
        item.setText(_translate("Form", "Age"))
        item = self.planeTable.horizontalHeaderItem(2)
        item.setText(_translate("Form", "Model ID"))
        item = self.planeTable.horizontalHeaderItem(3)
        item.setText(_translate("Form", "Capacity"))
        item = self.planeTable.horizontalHeaderItem(4)
        item.setText(_translate("Form", "Max Mileage"))
        item = self.planeTable.horizontalHeaderItem(5)
        item.setText(_translate("Form", "Min Air Level"))
        self.label_9.setText(_translate("Form", "Registration Number"))
        self.planeRegNum.setItemText(1, _translate("Form", "B-2165"))
        self.planeRegNum.setItemText(2, _translate("Form", "B-2178"))
        self.planeRegNum.setItemText(3, _translate("Form", "B-5165"))
        self.planeRegNum.setItemText(4, _translate("Form", "B-5332"))
        self.planeRegNum.setItemText(5, _translate("Form", "B-5552"))
        self.planeRegNum.setItemText(6, _translate("Form", "B-5983"))
        self.planeRegNum.setItemText(7, _translate("Form", "B-6312"))
        self.planeRegNum.setItemText(8, _translate("Form", "B-6443"))
        self.label_11.setText(_translate("Form", "Age"))
        self.label_12.setText(_translate("Form", "Model ID"))
        self.planeModelID.setItemText(1, _translate("Form", "A321"))
        self.planeModelID.setItemText(2, _translate("Form", "737-800"))
        self.searchPlane.setText(_translate("Form", "Search"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_4), _translate("Form", "Plane Information"))
        self.label_10.setText(_translate("Form", "Please select a airport:"))
        item = self.tableWidget_3.verticalHeaderItem(0)
        item.setText(_translate("Form", "1"))
        item = self.tableWidget_3.verticalHeaderItem(1)
        item.setText(_translate("Form", "2"))
        item = self.tableWidget_3.verticalHeaderItem(2)
        item.setText(_translate("Form", "3"))
        item = self.tableWidget_3.verticalHeaderItem(3)
        item.setText(_translate("Form", "4"))
        item = self.tableWidget_3.verticalHeaderItem(4)
        item.setText(_translate("Form", "5"))
        item = self.tableWidget_3.horizontalHeaderItem(0)
        item.setText(_translate("Form", "IATA"))
        item = self.tableWidget_3.horizontalHeaderItem(1)
        item.setText(_translate("Form", "Full Name"))
        item = self.tableWidget_3.horizontalHeaderItem(2)
        item.setText(_translate("Form", "Flight Zone Grade"))
        item = self.tableWidget_3.horizontalHeaderItem(3)
        item.setText(_translate("Form", "Max Flight Per Day"))
        __sortingEnabled = self.tableWidget_3.isSortingEnabled()
        self.tableWidget_3.setSortingEnabled(False)
        self.tableWidget_3.setSortingEnabled(__sortingEnabled)
        self.comboBox_6.setItemText(0, _translate("Form", "All"))
        self.comboBox_6.setItemText(1, _translate("Form", "Shenzhen (SZX)"))
        self.comboBox_6.setItemText(2, _translate("Form", "Beijing (PEK)"))
        self.comboBox_6.setItemText(3, _translate("Form", "Nanchang (KHN)"))
        self.comboBox_6.setItemText(4, _translate("Form", "Guangdong (CAN)"))
        self.comboBox_6.setItemText(5, _translate("Form", "Shanghai Pudong (PVG)"))
        self.comboBox_6.setItemText(6, _translate("Form", "Shanghai Hongqiao (SHA)"))
        self.comboBox_6.setItemText(7, _translate("Form", "Hangzhou (HGH)"))
        self.searchAirport.setText(_translate("Form", "Search"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), _translate("Form", "Airport Information"))
        self.newRegNum.setItemText(0, _translate("Form", "B-2165"))
        self.newRegNum.setItemText(1, _translate("Form", "B-2178"))
        self.newRegNum.setItemText(2, _translate("Form", "B-5165"))
        self.newRegNum.setItemText(3, _translate("Form", "B-5332"))
        self.newRegNum.setItemText(4, _translate("Form", "B-5552"))
        self.newRegNum.setItemText(5, _translate("Form", "B-5983"))
        self.newRegNum.setItemText(6, _translate("Form", "B-6312"))
        self.newRegNum.setItemText(7, _translate("Form", "B-6443"))
        self.label_23.setText(_translate("Form", "Pilot ID"))
        self.label_25.setText(_translate("Form", "Passenger Num."))
        self.label_26.setText(_translate("Form", "Flight Code"))
        self.newPilotID.setItemText(0, _translate("Form", "P001"))
        self.newPilotID.setItemText(1, _translate("Form", "P002"))
        self.newPilotID.setItemText(2, _translate("Form", "P003"))
        self.newPilotID.setItemText(3, _translate("Form", "P004"))
        self.newPilotID.setItemText(4, _translate("Form", "P005"))
        self.newPilotID.setItemText(5, _translate("Form", "P006"))
        self.newPilotID.setItemText(6, _translate("Form", "P007"))
        self.newPilotID.setItemText(7, _translate("Form", "P008"))
        self.label_19.setText(_translate("Form", "Dep. Time"))
        self.label_28.setText(_translate("Form", "LG"))
        self.label_17.setText(_translate("Form", "Reg. Num."))
        self.label_27.setText(_translate("Form", "Date"))
        self.label_21.setText(_translate("Form", "Dep. FCC"))
        self.label_22.setText(_translate("Form", "Arr. Time"))
        self.label_20.setText(_translate("Form", "Arr. FCC"))
        self.label_24.setText(_translate("Form", "StopBy FCC (Optional)"))
        self.newDepFCCCode.setItemText(0, _translate("Form", "Shenzhen (SZX)"))
        self.newDepFCCCode.setItemText(1, _translate("Form", "Beijing (PEK)"))
        self.newDepFCCCode.setItemText(2, _translate("Form", "Nanchang (KHN)"))
        self.newDepFCCCode.setItemText(3, _translate("Form", "Chengdu (CTU)"))
        self.newDepFCCCode.setItemText(4, _translate("Form", "Guangzhou (CAN)"))
        self.newDepFCCCode.setItemText(5, _translate("Form", "Hangzhou (HGH)"))
        self.newDepFCCCode.setItemText(6, _translate("Form", "Wuhan (WUH)"))
        self.newDepFCCCode.setItemText(7, _translate("Form", "Shanghai Pudong (PVG)"))
        self.newDepFCCCode.setItemText(8, _translate("Form", "Shanghai Hongqiao (SHA)"))
        self.newDepFCCCode.setItemText(9, _translate("Form", "Xi\'an (XIY)"))
        self.newArrFCCCode.setItemText(0, _translate("Form", "Beijing (PEK)"))
        self.newArrFCCCode.setItemText(1, _translate("Form", "Shenzhen (SZX)"))
        self.newArrFCCCode.setItemText(2, _translate("Form", "Nanchang (KHN)"))
        self.newArrFCCCode.setItemText(3, _translate("Form", "Chengdu (CTU)"))
        self.newArrFCCCode.setItemText(4, _translate("Form", "Guangzhou (CAN)"))
        self.newArrFCCCode.setItemText(5, _translate("Form", "Hangzhou (HGH)"))
        self.newArrFCCCode.setItemText(6, _translate("Form", "Wuhan (WUH)"))
        self.newArrFCCCode.setItemText(7, _translate("Form", "Shanghai Pudong (PVG)"))
        self.newArrFCCCode.setItemText(8, _translate("Form", "Shanghai Hongqiao (SHA)"))
        self.newArrFCCCode.setItemText(9, _translate("Form", "Xi\'an (XIY)"))
        self.newStpFCCCode.setItemText(1, _translate("Form", "Beijing (PEK)"))
        self.newStpFCCCode.setItemText(2, _translate("Form", "Shenzhen (SZX)"))
        self.newStpFCCCode.setItemText(3, _translate("Form", "Nanchang (KHN)"))
        self.newStpFCCCode.setItemText(4, _translate("Form", "Chengdu (CTU)"))
        self.newStpFCCCode.setItemText(5, _translate("Form", "Guangzhou (CAN)"))
        self.newStpFCCCode.setItemText(6, _translate("Form", "Hangzhou (HGH)"))
        self.newStpFCCCode.setItemText(7, _translate("Form", "Wuhan (WUH)"))
        self.newStpFCCCode.setItemText(8, _translate("Form", "Shanghai Pudong (PVG)"))
        self.newStpFCCCode.setItemText(9, _translate("Form", "Shanghai Hongqiao (SHA)"))
        self.newStpFCCCode.setItemText(10, _translate("Form", "Xi\'an (XIY)"))
        item = self.tableWidget_6.verticalHeaderItem(0)
        item.setText(_translate("Form", "1"))
        item = self.tableWidget_6.verticalHeaderItem(1)
        item.setText(_translate("Form", "2"))
        item = self.tableWidget_6.verticalHeaderItem(2)
        item.setText(_translate("Form", "3"))
        item = self.tableWidget_6.verticalHeaderItem(3)
        item.setText(_translate("Form", "4"))
        item = self.tableWidget_6.verticalHeaderItem(4)
        item.setText(_translate("Form", "5"))
        item = self.tableWidget_6.verticalHeaderItem(5)
        item.setText(_translate("Form", "6"))
        item = self.tableWidget_6.verticalHeaderItem(6)
        item.setText(_translate("Form", "7"))
        item = self.tableWidget_6.verticalHeaderItem(7)
        item.setText(_translate("Form", "8"))
        item = self.tableWidget_6.verticalHeaderItem(8)
        item.setText(_translate("Form", "9"))
        item = self.tableWidget_6.verticalHeaderItem(9)
        item.setText(_translate("Form", "10"))
        item = self.tableWidget_6.verticalHeaderItem(10)
        item.setText(_translate("Form", "11"))
        item = self.tableWidget_6.verticalHeaderItem(11)
        item.setText(_translate("Form", "12"))
        item = self.tableWidget_6.verticalHeaderItem(12)
        item.setText(_translate("Form", "13"))
        item = self.tableWidget_6.horizontalHeaderItem(0)
        item.setText(_translate("Form", "Flight Code"))
        item = self.tableWidget_6.horizontalHeaderItem(1)
        item.setText(_translate("Form", "Reg. Num."))
        item = self.tableWidget_6.horizontalHeaderItem(2)
        item.setText(_translate("Form", "Date"))
        item = self.tableWidget_6.horizontalHeaderItem(3)
        item.setText(_translate("Form", "Dep. Time"))
        item = self.tableWidget_6.horizontalHeaderItem(4)
        item.setText(_translate("Form", "Dep. FCC"))
        item = self.tableWidget_6.horizontalHeaderItem(5)
        item.setText(_translate("Form", "StopBy FCC"))
        item = self.tableWidget_6.horizontalHeaderItem(6)
        item.setText(_translate("Form", "Arr. Time"))
        item = self.tableWidget_6.horizontalHeaderItem(7)
        item.setText(_translate("Form", "Arr. FCC"))
        item = self.tableWidget_6.horizontalHeaderItem(8)
        item.setText(_translate("Form", "Pilot ID"))
        item = self.tableWidget_6.horizontalHeaderItem(9)
        item.setText(_translate("Form", "Psg. Num."))
        __sortingEnabled = self.tableWidget_6.isSortingEnabled()
        self.tableWidget_6.setSortingEnabled(False)
        self.tableWidget_6.setSortingEnabled(__sortingEnabled)
        self.insertFlight.setText(_translate("Form", "Insert"))
        self.deleteFlight.setText(_translate("Form", "Delete"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_5), _translate("Form", "Flight Management"))

