# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'dialog.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(671, 409)
        self.IDedit = QtWidgets.QLineEdit(Dialog)
        self.IDedit.setGeometry(QtCore.QRect(175, 23, 113, 20))
        self.IDedit.setObjectName("IDedit")
        self.foedit = QtWidgets.QTextEdit(Dialog)
        self.foedit.setGeometry(QtCore.QRect(525, 113, 121, 81))
        self.foedit.setObjectName("foedit")
        self.firstofficer_2 = QtWidgets.QLabel(Dialog)
        self.firstofficer_2.setGeometry(QtCore.QRect(375, 264, 121, 21))
        font = QtGui.QFont()
        font.setFamily("3ds")
        font.setPointSize(12)
        self.firstofficer_2.setFont(font)
        self.firstofficer_2.setObjectName("firstofficer_2")
        self.FID = QtWidgets.QLabel(Dialog)
        self.FID.setGeometry(QtCore.QRect(25, 23, 71, 21))
        font = QtGui.QFont()
        font.setFamily("3ds")
        font.setPointSize(12)
        self.FID.setFont(font)
        self.FID.setObjectName("FID")
        self.captain = QtWidgets.QLabel(Dialog)
        self.captain.setGeometry(QtCore.QRect(375, 63, 91, 21))
        font = QtGui.QFont()
        font.setFamily("3ds")
        font.setPointSize(12)
        self.captain.setFont(font)
        self.captain.setObjectName("captain")
        self.alter = QtWidgets.QPushButton(Dialog)
        self.alter.setGeometry(QtCore.QRect(336, 354, 91, 30))
        font = QtGui.QFont()
        font.setFamily("3ds")
        font.setPointSize(12)
        self.alter.setFont(font)
        self.alter.setObjectName("alter")
        self.delete_2 = QtWidgets.QPushButton(Dialog)
        self.delete_2.setGeometry(QtCore.QRect(446, 354, 91, 30))
        font = QtGui.QFont()
        font.setFamily("3ds")
        font.setPointSize(12)
        self.delete_2.setFont(font)
        self.delete_2.setObjectName("delete_2")
        self.FCode = QtWidgets.QLabel(Dialog)
        self.FCode.setGeometry(QtCore.QRect(25, 63, 91, 21))
        font = QtGui.QFont()
        font.setFamily("3ds")
        font.setPointSize(12)
        self.FCode.setFont(font)
        self.FCode.setObjectName("FCode")
        self.foedit_2 = QtWidgets.QTextEdit(Dialog)
        self.foedit_2.setGeometry(QtCore.QRect(525, 223, 121, 101))
        self.foedit_2.setObjectName("foedit_2")
        self.depPortedit = QtWidgets.QLineEdit(Dialog)
        self.depPortedit.setGeometry(QtCore.QRect(175, 226, 113, 20))
        self.depPortedit.setObjectName("depPortedit")
        self.regnumedit = QtWidgets.QLineEdit(Dialog)
        self.regnumedit.setGeometry(QtCore.QRect(525, 23, 121, 20))
        self.regnumedit.setText("")
        self.regnumedit.setObjectName("regnumedit")
        self.arrtimeEdit = QtWidgets.QTimeEdit(Dialog)
        self.arrtimeEdit.setGeometry(QtCore.QRect(175, 184, 118, 22))
        self.arrtimeEdit.setObjectName("arrtimeEdit")
        self.FDate = QtWidgets.QLabel(Dialog)
        self.FDate.setGeometry(QtCore.QRect(25, 103, 81, 21))
        font = QtGui.QFont()
        font.setFamily("3ds")
        font.setPointSize(12)
        self.FDate.setFont(font)
        self.FDate.setObjectName("FDate")
        self.depport = QtWidgets.QLineEdit(Dialog)
        self.depport.setGeometry(QtCore.QRect(175, 266, 113, 20))
        self.depport.setObjectName("depport")
        self.ArrTime = QtWidgets.QLabel(Dialog)
        self.ArrTime.setGeometry(QtCore.QRect(25, 183, 91, 21))
        font = QtGui.QFont()
        font.setFamily("3ds")
        font.setPointSize(12)
        self.ArrTime.setFont(font)
        self.ArrTime.setObjectName("ArrTime")
        self.Codeedit = QtWidgets.QLineEdit(Dialog)
        self.Codeedit.setGeometry(QtCore.QRect(175, 63, 113, 20))
        self.Codeedit.setObjectName("Codeedit")
        self.num = QtWidgets.QLabel(Dialog)
        self.num.setGeometry(QtCore.QRect(25, 306, 121, 21))
        font = QtGui.QFont()
        font.setFamily("3ds")
        font.setPointSize(12)
        self.num.setFont(font)
        self.num.setObjectName("num")
        self.capedit = QtWidgets.QLineEdit(Dialog)
        self.capedit.setGeometry(QtCore.QRect(525, 63, 121, 20))
        self.capedit.setObjectName("capedit")
        self.exit = QtWidgets.QPushButton(Dialog)
        self.exit.setGeometry(QtCore.QRect(555, 354, 91, 31))
        font = QtGui.QFont()
        font.setFamily("3ds")
        font.setPointSize(12)
        self.exit.setFont(font)
        self.exit.setObjectName("exit")
        self.regnum = QtWidgets.QLabel(Dialog)
        self.regnum.setGeometry(QtCore.QRect(375, 23, 121, 21))
        font = QtGui.QFont()
        font.setFamily("3ds")
        font.setPointSize(12)
        self.regnum.setFont(font)
        self.regnum.setObjectName("regnum")
        self.DepTime = QtWidgets.QLabel(Dialog)
        self.DepTime.setGeometry(QtCore.QRect(25, 143, 91, 21))
        font = QtGui.QFont()
        font.setFamily("3ds")
        font.setPointSize(12)
        self.DepTime.setFont(font)
        self.DepTime.setObjectName("DepTime")
        self.firstofficer = QtWidgets.QLabel(Dialog)
        self.firstofficer.setGeometry(QtCore.QRect(375, 143, 121, 21))
        font = QtGui.QFont()
        font.setFamily("3ds")
        font.setPointSize(12)
        self.firstofficer.setFont(font)
        self.firstofficer.setObjectName("firstofficer")
        self.arrport = QtWidgets.QLabel(Dialog)
        self.arrport.setGeometry(QtCore.QRect(25, 266, 91, 21))
        font = QtGui.QFont()
        font.setFamily("3ds")
        font.setPointSize(12)
        self.arrport.setFont(font)
        self.arrport.setObjectName("arrport")
        self.FID_2 = QtWidgets.QLabel(Dialog)
        self.FID_2.setGeometry(QtCore.QRect(25, 226, 101, 21))
        font = QtGui.QFont()
        font.setFamily("3ds")
        font.setPointSize(12)
        self.FID_2.setFont(font)
        self.FID_2.setObjectName("FID_2")
        self.deptimeEdit = QtWidgets.QTimeEdit(Dialog)
        self.deptimeEdit.setGeometry(QtCore.QRect(175, 143, 118, 22))
        self.deptimeEdit.setObjectName("deptimeEdit")
        self.numedit = QtWidgets.QLineEdit(Dialog)
        self.numedit.setGeometry(QtCore.QRect(175, 306, 113, 20))
        self.numedit.setObjectName("numedit")
        self.dateEdit = QtWidgets.QDateEdit(Dialog)
        self.dateEdit.setGeometry(QtCore.QRect(175, 104, 111, 21))
        self.dateEdit.setDateTime(QtCore.QDateTime(QtCore.QDate(2019, 5, 3), QtCore.QTime(0, 0, 0)))
        self.dateEdit.setMaximumDateTime(QtCore.QDateTime(QtCore.QDate(2019, 5, 30), QtCore.QTime(0, 0, 0)))
        self.dateEdit.setMinimumDateTime(QtCore.QDateTime(QtCore.QDate(2019, 3, 15), QtCore.QTime(0, 0, 0)))
        self.dateEdit.setObjectName("dateEdit")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.firstofficer_2.setText(_translate("Dialog", "Cabin Crew"))
        self.FID.setText(_translate("Dialog", "Flight ID"))
        self.captain.setText(_translate("Dialog", "Captain ID"))
        self.alter.setText(_translate("Dialog", "Alter"))
        self.delete_2.setText(_translate("Dialog", "Delete"))
        self.FCode.setText(_translate("Dialog", "Flight Code"))
        self.FDate.setText(_translate("Dialog", "Flight Date"))
        self.ArrTime.setText(_translate("Dialog", "Arr. Time"))
        self.num.setText(_translate("Dialog", "Passenger Num"))
        self.exit.setText(_translate("Dialog", "Exit"))
        self.regnum.setText(_translate("Dialog", "Plane Reg. Num"))
        self.DepTime.setText(_translate("Dialog", "Dep. Time"))
        self.firstofficer.setText(_translate("Dialog", "First Officer"))
        self.arrport.setText(_translate("Dialog", "Arr. Airport"))
        self.FID_2.setText(_translate("Dialog", "Dep. Airport"))

