# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'popupwindow.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(684, 410)
        self.FCode = QtWidgets.QLabel(Form)
        self.FCode.setGeometry(QtCore.QRect(29, 65, 91, 21))
        font = QtGui.QFont()
        font.setFamily("3ds")
        font.setPointSize(12)
        self.FCode.setFont(font)
        self.FCode.setObjectName("FCode")
        self.FID = QtWidgets.QLabel(Form)
        self.FID.setGeometry(QtCore.QRect(29, 25, 71, 21))
        font = QtGui.QFont()
        font.setFamily("3ds")
        font.setPointSize(12)
        self.FID.setFont(font)
        self.FID.setObjectName("FID")
        self.IDedit = QtWidgets.QLineEdit(Form)
        self.IDedit.setGeometry(QtCore.QRect(179, 25, 113, 20))
        self.IDedit.setObjectName("IDedit")
        self.Codeedit = QtWidgets.QLineEdit(Form)
        self.Codeedit.setGeometry(QtCore.QRect(179, 65, 113, 20))
        self.Codeedit.setObjectName("Codeedit")
        self.DepTime = QtWidgets.QLabel(Form)
        self.DepTime.setGeometry(QtCore.QRect(29, 145, 91, 21))
        font = QtGui.QFont()
        font.setFamily("3ds")
        font.setPointSize(12)
        self.DepTime.setFont(font)
        self.DepTime.setObjectName("DepTime")
        self.FDate = QtWidgets.QLabel(Form)
        self.FDate.setGeometry(QtCore.QRect(29, 105, 81, 21))
        font = QtGui.QFont()
        font.setFamily("3ds")
        font.setPointSize(12)
        self.FDate.setFont(font)
        self.FDate.setObjectName("FDate")
        self.dateEdit = QtWidgets.QDateEdit(Form)
        self.dateEdit.setGeometry(QtCore.QRect(179, 106, 111, 21))
        self.dateEdit.setDateTime(QtCore.QDateTime(QtCore.QDate(2019, 5, 3), QtCore.QTime(0, 0, 0)))
        self.dateEdit.setMaximumDateTime(QtCore.QDateTime(QtCore.QDate(2019, 5, 30), QtCore.QTime(0, 0, 0)))
        self.dateEdit.setMinimumDateTime(QtCore.QDateTime(QtCore.QDate(2019, 3, 15), QtCore.QTime(0, 0, 0)))
        self.dateEdit.setObjectName("dateEdit")
        self.ArrTime = QtWidgets.QLabel(Form)
        self.ArrTime.setGeometry(QtCore.QRect(29, 185, 91, 21))
        font = QtGui.QFont()
        font.setFamily("3ds")
        font.setPointSize(12)
        self.ArrTime.setFont(font)
        self.ArrTime.setObjectName("ArrTime")
        self.deptimeEdit = QtWidgets.QTimeEdit(Form)
        self.deptimeEdit.setGeometry(QtCore.QRect(179, 145, 118, 22))
        self.deptimeEdit.setObjectName("deptimeEdit")
        self.arrtimeEdit = QtWidgets.QTimeEdit(Form)
        self.arrtimeEdit.setGeometry(QtCore.QRect(179, 186, 118, 22))
        self.arrtimeEdit.setObjectName("arrtimeEdit")
        self.num = QtWidgets.QLabel(Form)
        self.num.setGeometry(QtCore.QRect(29, 308, 121, 21))
        font = QtGui.QFont()
        font.setFamily("3ds")
        font.setPointSize(12)
        self.num.setFont(font)
        self.num.setObjectName("num")
        self.numedit = QtWidgets.QLineEdit(Form)
        self.numedit.setGeometry(QtCore.QRect(179, 308, 113, 20))
        self.numedit.setObjectName("numedit")
        self.depport = QtWidgets.QLineEdit(Form)
        self.depport.setGeometry(QtCore.QRect(179, 268, 113, 20))
        self.depport.setObjectName("depport")
        self.arrport = QtWidgets.QLabel(Form)
        self.arrport.setGeometry(QtCore.QRect(29, 268, 91, 21))
        font = QtGui.QFont()
        font.setFamily("3ds")
        font.setPointSize(12)
        self.arrport.setFont(font)
        self.arrport.setObjectName("arrport")
        self.FID_2 = QtWidgets.QLabel(Form)
        self.FID_2.setGeometry(QtCore.QRect(29, 228, 101, 21))
        font = QtGui.QFont()
        font.setFamily("3ds")
        font.setPointSize(12)
        self.FID_2.setFont(font)
        self.FID_2.setObjectName("FID_2")
        self.depPortedit = QtWidgets.QLineEdit(Form)
        self.depPortedit.setGeometry(QtCore.QRect(179, 228, 113, 20))
        self.depPortedit.setObjectName("depPortedit")
        self.regnum = QtWidgets.QLabel(Form)
        self.regnum.setGeometry(QtCore.QRect(379, 25, 121, 21))
        font = QtGui.QFont()
        font.setFamily("3ds")
        font.setPointSize(12)
        self.regnum.setFont(font)
        self.regnum.setObjectName("regnum")
        self.capedit = QtWidgets.QLineEdit(Form)
        self.capedit.setGeometry(QtCore.QRect(529, 65, 121, 20))
        self.capedit.setObjectName("capedit")
        self.regnumedit = QtWidgets.QLineEdit(Form)
        self.regnumedit.setGeometry(QtCore.QRect(529, 25, 121, 20))
        self.regnumedit.setText("")
        self.regnumedit.setObjectName("regnumedit")
        self.captain = QtWidgets.QLabel(Form)
        self.captain.setGeometry(QtCore.QRect(379, 65, 91, 21))
        font = QtGui.QFont()
        font.setFamily("3ds")
        font.setPointSize(12)
        self.captain.setFont(font)
        self.captain.setObjectName("captain")
        self.firstofficer = QtWidgets.QLabel(Form)
        self.firstofficer.setGeometry(QtCore.QRect(379, 145, 121, 21))
        font = QtGui.QFont()
        font.setFamily("3ds")
        font.setPointSize(12)
        self.firstofficer.setFont(font)
        self.firstofficer.setObjectName("firstofficer")
        self.foedit = QtWidgets.QTextEdit(Form)
        self.foedit.setGeometry(QtCore.QRect(529, 115, 121, 81))
        self.foedit.setObjectName("foedit")
        self.foedit_2 = QtWidgets.QTextEdit(Form)
        self.foedit_2.setGeometry(QtCore.QRect(529, 225, 121, 101))
        self.foedit_2.setObjectName("foedit_2")
        self.firstofficer_2 = QtWidgets.QLabel(Form)
        self.firstofficer_2.setGeometry(QtCore.QRect(379, 266, 121, 21))
        font = QtGui.QFont()
        font.setFamily("3ds")
        font.setPointSize(12)
        self.firstofficer_2.setFont(font)
        self.firstofficer_2.setObjectName("firstofficer_2")
        self.exit = QtWidgets.QPushButton(Form)
        self.exit.setGeometry(QtCore.QRect(559, 356, 91, 31))
        font = QtGui.QFont()
        font.setFamily("3ds")
        font.setPointSize(12)
        self.exit.setFont(font)
        self.exit.setObjectName("exit")
        self.delete_2 = QtWidgets.QPushButton(Form)
        self.delete_2.setGeometry(QtCore.QRect(450, 356, 91, 30))
        font = QtGui.QFont()
        font.setFamily("3ds")
        font.setPointSize(12)
        self.delete_2.setFont(font)
        self.delete_2.setObjectName("delete_2")
        self.alter = QtWidgets.QPushButton(Form)
        self.alter.setGeometry(QtCore.QRect(340, 356, 91, 30))
        font = QtGui.QFont()
        font.setFamily("3ds")
        font.setPointSize(12)
        self.alter.setFont(font)
        self.alter.setObjectName("alter")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Details"))
        self.FCode.setText(_translate("Form", "Flight Code"))
        self.FID.setText(_translate("Form", "Flight ID"))
        self.DepTime.setText(_translate("Form", "Dep. Time"))
        self.FDate.setText(_translate("Form", "Flight Date"))
        self.ArrTime.setText(_translate("Form", "Arr. Time"))
        self.num.setText(_translate("Form", "Passenger Num"))
        self.arrport.setText(_translate("Form", "Arr. Airport"))
        self.FID_2.setText(_translate("Form", "Dep. Airport"))
        self.regnum.setText(_translate("Form", "Plane Reg. Num"))
        self.captain.setText(_translate("Form", "Captain ID"))
        self.firstofficer.setText(_translate("Form", "First Officer"))
        self.firstofficer_2.setText(_translate("Form", "Cabin Crew"))
        self.exit.setText(_translate("Form", "Exit"))
        self.delete_2.setText(_translate("Form", "Delete"))
        self.alter.setText(_translate("Form", "Alter"))

